#!/bin/bash

# Supabase project details
PROJECT_REF="fpomqateqebxypbjabch"
SUPABASE_URL="https://fpomqateqebxypbjabch.supabase.co"
SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwb21xYXRlcWVieHlwYmphYmNoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjQyMDIwMywiZXhwIjoyMDc3OTk2MjAzfQ.jzP0aFLZrwgrzEPM1NTDEGMOOxZhX8NnBbsl_ksxzDA"

echo "================================================"
echo "Supabase Migration Application Script"
echo "================================================"
echo ""
echo "To apply migrations to your Supabase database, you have two options:"
echo ""
echo "OPTION 1: Via Supabase Dashboard (RECOMMENDED)"
echo "---------------------------------------------"
echo "1. Go to: https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"
echo "2. Copy and paste each migration file content from supabase/migrations/"
echo "3. Run them in this order:"
echo "   a. 20250727104830_remote_schema.sql"
echo "   b. 20250727110847_add_vocabulary_columns_to_flashcards.sql"
echo "   c. 20250727111453_create_admin_flashcard_function.sql"
echo "   d. 20250727111942_disable_rls_for_import.sql"
echo "   e. 20250727112139_fix_admin_function.sql"
echo ""
echo "OPTION 2: Via Command Line (requires database password)"
echo "--------------------------------------------------------"
echo "If you have the database password, you can use:"
echo ""
echo "  psql 'postgresql://postgres.fpomqateqebxypbjabch:[PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres' < supabase/migrations/20250727104830_remote_schema.sql"
echo ""
echo "You can find your database password at:"
echo "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/database"
echo ""
echo "================================================"
