-- Create vocabulary learning system tables
-- This migration creates tables for the "My Vocabulary" feature with spaced repetition

-- ============================================
-- 1. VOCABULARY DEFINITIONS (Shared Database)
-- ============================================
-- Stores vocabulary definitions shared across all users
-- Hybrid approach: AI-generated on first use, then reused
CREATE TABLE IF NOT EXISTS public.vocabulary_definitions (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    word TEXT NOT NULL UNIQUE,
    definition TEXT NOT NULL,
    vietnamese_translation TEXT,
    pronunciation TEXT, -- IPA notation
    word_type TEXT, -- noun, verb, adjective, collocation, phrase, etc.
    collocations TEXT[], -- Array of common phrases/collocations
    synonyms TEXT[],
    related_words TEXT[],
    usage_notes TEXT,
    ielts_band_level TEXT, -- 5.0-6.0, 6.5-7.0, 7.5+
    example_sentences JSONB, -- Array of example sentences
    times_used INTEGER DEFAULT 0, -- Track popularity
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 2. VOCABULARY TAGS (For categorization)
-- ============================================
CREATE TABLE IF NOT EXISTS public.vocabulary_tags (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- e.g., "environment", "business", "health"
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default tags matching essay topics
INSERT INTO public.vocabulary_tags (name, description) VALUES
    ('environment', 'Environmental and sustainability topics'),
    ('business', 'Business and economics'),
    ('education', 'Education and learning'),
    ('health', 'Health and medical topics'),
    ('technology', 'Technology and innovation'),
    ('culture', 'Cultural and social topics'),
    ('politics', 'Government and political topics'),
    ('law', 'Legal and justice topics'),
    ('general', 'General academic vocabulary')
ON CONFLICT (name) DO NOTHING;

-- ============================================
-- 3. VOCABULARY_TAGS Junction Table
-- ============================================
-- Many-to-many relationship: vocabulary can have multiple tags
CREATE TABLE IF NOT EXISTS public.vocabulary_definition_tags (
    vocabulary_id UUID REFERENCES public.vocabulary_definitions(id) ON DELETE CASCADE,
    tag_id UUID REFERENCES public.vocabulary_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (vocabulary_id, tag_id)
);

-- ============================================
-- 4. SAVED VOCABULARY (User-specific)
-- ============================================
-- Tracks vocabulary saved by each user from essays/ideas
CREATE TABLE IF NOT EXISTS public.saved_vocabulary (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    vocabulary_id UUID REFERENCES public.vocabulary_definitions(id) ON DELETE CASCADE NOT NULL,

    -- Source context
    source_type TEXT NOT NULL, -- 'essay_correction', 'ideas_generator', 'manual'
    essay_id UUID REFERENCES public.essays(id) ON DELETE SET NULL,
    example_sentence TEXT, -- The specific sentence from the essay (corrected version)

    -- Spaced repetition data
    mastery_level TEXT DEFAULT 'new', -- 'new', 'learning', 'practiced', 'mastered'
    last_reviewed_at TIMESTAMP WITH TIME ZONE,
    next_review_date TIMESTAMP WITH TIME ZONE,
    review_count INTEGER DEFAULT 0,

    -- Performance metrics
    pronunciation_plays INTEGER DEFAULT 0,
    exercises_completed INTEGER DEFAULT 0,
    exercises_correct INTEGER DEFAULT 0,

    -- Metadata
    is_flagged BOOLEAN DEFAULT FALSE, -- User can flag difficult words
    notes TEXT, -- User's personal notes
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Ensure user can't save same vocabulary twice
    UNIQUE(user_id, vocabulary_id)
);

-- ============================================
-- 5. VOCABULARY EXERCISE BANK (Shared)
-- ============================================
-- Stores exercises for vocabulary (hybrid approach)
-- Generated by AI on first use, then reused for other students
CREATE TABLE IF NOT EXISTS public.vocabulary_exercise_bank (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    vocabulary_id UUID REFERENCES public.vocabulary_definitions(id) ON DELETE CASCADE NOT NULL,
    exercise_type TEXT NOT NULL, -- 'mcq_meaning', 'mcq_context', 'fill_blank', 'sentence_writing'
    question TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    options JSONB, -- For MCQ: array of options
    explanation TEXT, -- Why this answer is correct
    difficulty_level TEXT, -- 'easy', 'medium', 'hard'
    times_used INTEGER DEFAULT 0, -- Track usage
    success_rate NUMERIC(3,2), -- Track how many students answer correctly
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- One exercise per type per vocabulary
    UNIQUE(vocabulary_id, exercise_type)
);

-- ============================================
-- 6. STUDENT SENTENCES (Production practice)
-- ============================================
-- Tracks sentences students write for vocabulary practice
CREATE TABLE IF NOT EXISTS public.student_sentences (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    saved_vocabulary_id UUID REFERENCES public.saved_vocabulary(id) ON DELETE CASCADE NOT NULL,
    sentence TEXT NOT NULL,
    is_correct BOOLEAN,
    ai_feedback JSONB, -- {correctedSentence, grammarTips, betterExample, encouragement}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 7. EXERCISE ATTEMPTS (Track performance)
-- ============================================
-- Tracks each exercise attempt for analytics and SRS
CREATE TABLE IF NOT EXISTS public.vocabulary_exercise_attempts (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    saved_vocabulary_id UUID REFERENCES public.saved_vocabulary(id) ON DELETE CASCADE NOT NULL,
    exercise_id UUID REFERENCES public.vocabulary_exercise_bank(id) ON DELETE SET NULL,
    exercise_type TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    time_taken_seconds INTEGER, -- Track how long it took
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES for Performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_vocabulary_definitions_word ON public.vocabulary_definitions(word);
CREATE INDEX IF NOT EXISTS idx_saved_vocabulary_user_id ON public.saved_vocabulary(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_vocabulary_next_review ON public.saved_vocabulary(next_review_date);
CREATE INDEX IF NOT EXISTS idx_saved_vocabulary_mastery ON public.saved_vocabulary(mastery_level);
CREATE INDEX IF NOT EXISTS idx_saved_vocabulary_essay_id ON public.saved_vocabulary(essay_id);
CREATE INDEX IF NOT EXISTS idx_vocabulary_exercise_bank_vocab_id ON public.vocabulary_exercise_bank(vocabulary_id);
CREATE INDEX IF NOT EXISTS idx_student_sentences_user_id ON public.student_sentences(user_id);
CREATE INDEX IF NOT EXISTS idx_exercise_attempts_user_id ON public.vocabulary_exercise_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_exercise_attempts_saved_vocab ON public.vocabulary_exercise_attempts(saved_vocabulary_id);

-- ============================================
-- GRANT PERMISSIONS
-- ============================================
GRANT ALL ON public.vocabulary_definitions TO authenticated;
GRANT ALL ON public.vocabulary_tags TO authenticated;
GRANT ALL ON public.vocabulary_definition_tags TO authenticated;
GRANT ALL ON public.saved_vocabulary TO authenticated;
GRANT ALL ON public.vocabulary_exercise_bank TO authenticated;
GRANT ALL ON public.student_sentences TO authenticated;
GRANT ALL ON public.vocabulary_exercise_attempts TO authenticated;

-- ============================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================
ALTER TABLE public.vocabulary_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vocabulary_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vocabulary_definition_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_vocabulary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vocabulary_exercise_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_sentences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vocabulary_exercise_attempts ENABLE ROW LEVEL SECURITY;

-- ============================================
-- RLS POLICIES: vocabulary_definitions (Read by all, write by system)
-- ============================================
CREATE POLICY "Everyone can read vocabulary definitions"
    ON public.vocabulary_definitions FOR SELECT
    USING (true);

CREATE POLICY "Authenticated users can insert vocabulary definitions"
    ON public.vocabulary_definitions FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can update vocabulary definitions"
    ON public.vocabulary_definitions FOR UPDATE
    USING (auth.uid() IS NOT NULL);

-- ============================================
-- RLS POLICIES: vocabulary_tags (Read by all)
-- ============================================
CREATE POLICY "Everyone can read vocabulary tags"
    ON public.vocabulary_tags FOR SELECT
    USING (true);

CREATE POLICY "Only admins can manage tags"
    ON public.vocabulary_tags FOR ALL
    USING (EXISTS (
        SELECT 1 FROM public.users
        WHERE id = auth.uid() AND role = 'admin'
    ));

-- ============================================
-- RLS POLICIES: vocabulary_definition_tags
-- ============================================
CREATE POLICY "Everyone can read vocabulary tag associations"
    ON public.vocabulary_definition_tags FOR SELECT
    USING (true);

CREATE POLICY "Authenticated users can create tag associations"
    ON public.vocabulary_definition_tags FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

-- ============================================
-- RLS POLICIES: saved_vocabulary (User-specific)
-- ============================================
CREATE POLICY "Users can read their own saved vocabulary"
    ON public.saved_vocabulary FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own saved vocabulary"
    ON public.saved_vocabulary FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own saved vocabulary"
    ON public.saved_vocabulary FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own saved vocabulary"
    ON public.saved_vocabulary FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================
-- RLS POLICIES: vocabulary_exercise_bank (Read by all)
-- ============================================
CREATE POLICY "Everyone can read vocabulary exercises"
    ON public.vocabulary_exercise_bank FOR SELECT
    USING (true);

CREATE POLICY "Authenticated users can insert exercises"
    ON public.vocabulary_exercise_bank FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can update exercise stats"
    ON public.vocabulary_exercise_bank FOR UPDATE
    USING (auth.uid() IS NOT NULL);

-- ============================================
-- RLS POLICIES: student_sentences (User-specific)
-- ============================================
CREATE POLICY "Users can read their own sentences"
    ON public.student_sentences FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own sentences"
    ON public.student_sentences FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own sentences"
    ON public.student_sentences FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================
-- RLS POLICIES: exercise_attempts (User-specific)
-- ============================================
CREATE POLICY "Users can read their own exercise attempts"
    ON public.vocabulary_exercise_attempts FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own exercise attempts"
    ON public.vocabulary_exercise_attempts FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- ============================================
-- COMMENTS for Documentation
-- ============================================
COMMENT ON TABLE public.vocabulary_definitions IS 'Shared vocabulary database with definitions, translations, and examples';
COMMENT ON TABLE public.vocabulary_tags IS 'Tags for categorizing vocabulary (environment, business, etc.)';
COMMENT ON TABLE public.vocabulary_definition_tags IS 'Many-to-many relationship between vocabulary and tags';
COMMENT ON TABLE public.saved_vocabulary IS 'User-specific saved vocabulary from essays with spaced repetition tracking';
COMMENT ON TABLE public.vocabulary_exercise_bank IS 'Shared exercise database (hybrid: AI-generated, then reused)';
COMMENT ON TABLE public.student_sentences IS 'Sentences written by students for vocabulary practice';
COMMENT ON TABLE public.vocabulary_exercise_attempts IS 'Tracks exercise attempts for analytics and SRS algorithms';

COMMENT ON COLUMN public.saved_vocabulary.mastery_level IS 'new -> learning -> practiced -> mastered';
COMMENT ON COLUMN public.saved_vocabulary.source_type IS 'essay_correction, ideas_generator, or manual';
COMMENT ON COLUMN public.saved_vocabulary.example_sentence IS 'Sentence from the corrected essay showing vocabulary usage';
COMMENT ON COLUMN public.vocabulary_exercise_bank.exercise_type IS 'mcq_meaning, mcq_context, fill_blank, sentence_writing';
